/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: "#0D0D0F",
          card: "#1A1A1F",
          elevated: "#242429",
          input: "#27272A",
        },
        accent: {
          violet: "#C084FC",
          pink: "#F472B6",
          green: "#34D399",
          gold: "#F5E642",
          "gold-deep": "#E8A020",
          amber: "#F59E0B",
        },
        txt: {
          primary: "#F4F4F5",
          secondary: "#A1A1AA",
          muted: "#52525B",
          inverse: "#0D0D0F",
        },
        border: {
          subtle: "#27272A",
          DEFAULT: "#3F3F46",
          strong: "#52525B",
        },
        status: {
          danger: "#F87171",
          success: "#34D399",
          warning: "#F59E0B",
          info: "#60A5FA",
        },
        dancer: {
          1: "#C084FC",
          2: "#F472B6",
          3: "#34D399",
          4: "#60A5FA",
          5: "#FB923C",
          6: "#F87171",
          7: "#A78BFA",
          8: "#4ADE80",
          9: "#FCD34D",
          10: "#67E8F9",
          11: "#F9A8D4",
          12: "#86EFAC",
        },
        adj: {
          platinum: "#C084FC",
          "platinum-bg": "#4C1D95",
          "high-gold": "#F59E0B",
          "high-gold-bg": "#451A03",
          gold: "#FCD34D",
          "gold-bg": "#713F12",
          "high-silver": "#94A3B8",
          "high-silver-bg": "#1E293B",
          silver: "#64748B",
          "silver-bg": "#0F172A",
        },
        badge: {
          "approved-bg": "#064E3B",
          "approved-text": "#34D399",
          "pending-bg": "#451A03",
          "pending-text": "#F59E0B",
          "personal-bg": "#1C1917",
          "personal-text": "#78716C",
          "teacher-bg": "#2E1065",
          "teacher-text": "#C084FC",
          "admin-bg": "#1E1B4B",
          "admin-text": "#818CF8",
          "owner-bg": "#4C1D95",
          "owner-text": "#DDD6FE",
        },
        nav: {
          bg: "#0D0D0F",
          active: "#C084FC",
          inactive: "#52525B",
          "badge-bg": "#F472B6",
          "badge-text": "#F4F4F5",
        },
      },
      fontFamily: {
        display: ["PlayfairDisplay_700Bold"],
        body: ["DMSans_400Regular"],
        "body-medium": ["DMSans_500Medium"],
        mono: ["JetBrainsMono_400Regular"],
      },
      borderRadius: {
        xs: "4px",
        sm: "8px",
        md: "10px",
        lg: "16px",
        xl: "20px",
        pill: "999px",
      },
      spacing: {
        "page-mobile": "20px",
        "page-desktop": "32px",
        "card-pad": "16px",
        "section-gap": "24px",
      },
    },
  },
  plugins: [],
};
